workspace = { members = ["rszlm-sys"] }

[package]
name = "rszlm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
authors = ["shiben"]
description = "ZLMediaKit rust api"
repository = "https://github.com/benshi/rszlm"
keywords = ["zlm", "zlmediakit", "rszlm"]

[dependencies]
rszlm-sys = { path = "./rszlm-sys" }
once_cell = "1.8"
anyhow = "1"


[dev-dependencies]
rszlm = { path = "./", features = ["static"] }
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7", features = ["full"] }
video-rs = "0.8"


[features]
default = []
static = ["rszlm-sys/static"]
webrtc = ["rszlm-sys/webrtc"]
