[package]
name = "gst"
version = "0.1.0"
edition = "2024"

[dependencies]
rszlm = { path = "../.." }
gstreamer = "0.24.1"
gstreamer-app = "0.24.0"
anyhow = "1.0"
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7", features = ["full"] }
